/**
 * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/* exported CKBUILDER_CONFIG */

var CKBUILDER_CONFIG = {
	skin: 'flat',
	ignore: [
		'bender.js',
		'.bender',
		'bender-err.log',
		'bender-out.log',
		'dev',
		'docs',
		'.DS_Store',
		'.editorconfig',
		'.gitignore',
		'.gitattributes',
		'gruntfile.js',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'less',
		'.mailmap',
		'node_modules',
		'package.json',
		'README.md',
		'tests'
	],
	plugins: {
		acronym: 1,
		annotation: 1,
		basicstyles: 1,
		clipboard: 1,
		colorbutton: 1,
		contextmenu: 1,
		defaultfontstyle: 1,
		dialog: 1,
		dialogadvtab: 1,
		dialogui: 1,
		divarea: 1,
		enterkey: 1,
		entities: 1,
		filebrowser: 1,
		filetools: 1,
		font: 1,
		format: 1,
		htmlwriter: 1,
		image: 1,
		image2: 1,
		indent: 1,
		indentblock: 1,
		indentlist: 1,
		justify: 1,
		lineheight: 1,
		lineutils: 1,
		link: 1,
		list: 1,
		maximize: 1,
		notification: 1,
		notificationaggregator: 1,
		oembed: 1,
		pagebreak: 1,
		pastefromword: 1,
		pastetext: 1,
		removeformat: 1,
		sharedspace: 1,
		stylescombo: 1,
		table: 1,
		tableresize: 1,
		tabletools: 1,
		toolbar: 1,
		undo: 1,
		uploadimage:1,
		uploadwidget: 1,
		quicktable: 1,
		widget: 1,
		wittyanchor: 1,
		wittyprint: 1,
		wittyupload: 1
	}
};
